version: '2'
services:
    testonline-app:
        image: testonline
        environment:
            - _JAVA_OPTIONS=-Xmx512m -Xms256m
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mariadb://testonline-mariadb:3306/testonline
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    testonline-mariadb:
        extends:
            file: mariadb.yml
            service: testonline-mariadb
